[fmt]
line_length = 99
tab_width = 4
bracket_spacing = false
quote_style = "double"

[profile.default]
src = "contracts"
test = "tests"
script = "scripts"
out = "forge-out"
libs = ["lib"]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink/",
    "v3-core/=lib/v3-core/contracts/"
]

[fuzz]
runs = 1000

[rpc_endpoints]
arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC}"
bartio = "${BARTIO_RPC}"
imola = "${IMOLA_RPC}"

[etherscan]
arbitrum-sepolia = { key = "${ARBISCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
